package com.rst.mywallet.model;

public enum AccountStatus {

	PENDING, ACTIVE, BLOCKED, OK, BAD_REQUEST, UNAUTHORIZED, VALIDATION_EXCEPTION, EXCEPTION, WRONG_CREDENTIALS, ACCESS_DENIED, NOT_FOUND, DUPLICATE_ENTITY;
}
